const products = [
  {
    product_id: 1,
    licence_name: "Pokemon",
    category_name: "Figuras coleccionables",
    product_name: "Pidgeotto",
    product_description: "Figura coleccionable pokemon",
    product_price: 1799.99,
    dues: 10,
    product_sku: "PKM001001",
    img_front: "/img/pokemon/pidgeotto-box.webp",
    img_back: "/img/pokemon/pidgeotto-1.webp",
  },
  {
    product_id: 2,
    licence_name: "STAR WARS",
    category_name: "Figuras coleccionables",
    product_name: "STORMTROOMPER LIGHTSABER",
    product_description: "Figura coleccionable star wars",
    product_price: 1799.99,
    dues: 10,
    product_sku: "PKM001001",
    img_front: "/img/star-wars/trooper-box.webp",
    img_back: "/img/pokemon/trooper-1.webp",
  },
  {
    product_id: 3,
    licence_name: "Pokemon",
    category_name: "Figuras coleccionables",
    product_name: "Charmander",
    product_description: "Figura coleccionable pokemon",
    product_price: 700,
    dues: 10,
    product_sku: "PKM001001",
    img_front: "/img/pokemon/charmander-1.webp",
    img_back: "/img/pokemon/charmander-box.webp",
  },
  {
    product_id: 4,
    licence_name: "STAR WARS",
    category_name: "Figuras coleccionables",
    product_name: "BABY YODA",
    product_description: "Figura coleccionable star wars",
    product_price: 1799.99,
    dues: 10,
    product_sku: "PKM001001",
    img_front: "img/star-wars/baby-yado-box.webp",
    img_back: "/img/pokemon/baby-yado-1.webp",
  },
];

const shopControllers = {
  shop: (req, res) => res.render("pages/shop/shop", { products: products }),
  shopItem: (req, res) => res.render("pages/shop/item"),
  shopItemAdd: (req, res) => res.send("Route for Item add view"),
  cart: (req, res) => res.render("pages/shop/cart"),
  checkout: (req, res) => res.send("Route for Checkout view"),
};

module.exports = shopControllers;
